'use client'

import { Header } from '@/components/layout/Header'
import { Footer } from '@/components/layout/Footer'

export default function TermsPage() {
    return (
        <div className="min-h-screen bg-[#0a0e27] text-white font-sans">
            <Header />

            <main className="pt-32 pb-24 px-6 md:px-12 relative">
                <div className="fixed inset-0 bg-gradient-to-br from-[#0a0e27] via-[#0f172a] to-[#1a1f3a] -z-10" />

                <div className="container mx-auto max-w-4xl bg-black/20 backdrop-blur-xl border border-white/10 rounded-3xl p-8 md:p-12 space-y-12">

                    <div className="border-b border-white/10 pb-8">
                        <h1 className="text-4xl md:text-5xl font-bold mb-4">Terms of Service</h1>
                        <p className="text-white/60">Last updated: December 2024</p>
                    </div>

                    <div className="space-y-12 text-white/80 leading-relaxed">

                        <section className="space-y-4">
                            <h2 className="text-2xl font-bold text-white">1. Acceptance of Terms and Conditions</h2>
                            <p>
                                These Terms of Service (&quot;Terms&quot;, &quot;Agreement&quot;) constitute a legally binding agreement between you (&quot;User&quot;, &quot;you&quot;, &quot;your&quot;) and Beexel Graphics (&quot;Company&quot;, &quot;we&quot;, &quot;us&quot;, &quot;our&quot;) governing your use of the Beexel Render Pro service (&quot;Service&quot;). By accessing, browsing, or otherwise using the Service, you acknowledge that you have read, understood, and agree to be bound by these Terms and all applicable laws and regulations. If you do not agree with any part of these Terms, you must not use the Service.
                            </p>
                            <p>
                                We reserve the right to modify these Terms at any time without prior notice. Your continued use of the Service after any such modifications constitutes your acceptance of the new Terms. It is your responsibility to review these Terms periodically for any changes.
                            </p>
                        </section>

                        <section className="space-y-4">
                            <h2 className="text-2xl font-bold text-white">2. Service Description and Scope</h2>
                            <p>
                                Beexel Render Pro is a proprietary AI-powered architectural rendering and enhancement service that utilizes advanced artificial intelligence technologies, including but not limited to Stable Diffusion models and third-party AI service providers, to generate, enhance, and transform architectural visualizations. The Service provides users with the ability to upload digital images and receive AI-generated architectural renders, enhancements, and modifications.
                            </p>
                            <p>
                                The Service is provided on an "as is" and "as available" basis. We do not guarantee that the Service will be uninterrupted, error-free, or completely secure. The Service may be temporarily unavailable due to maintenance, updates, technical difficulties, or third-party service provider issues beyond our control.
                            </p>
                        </section>

                        <section className="space-y-4">
                            <h2 className="text-2xl font-bold text-white">3. Intellectual Property Rights and User Ownership</h2>
                            <h3 className="text-xl font-semibold text-white/90">3.1 User Content Ownership</h3>
                            <p>
                                You retain full and exclusive ownership of all rights, title, and interest in and to any images, data, or content you upload, submit, or transmit through the Service ("User Content"). Nothing in these Terms shall be construed as transferring any ownership rights in your User Content to us or any third party.
                            </p>

                            <h3 className="text-xl font-semibold text-white/90">3.2 Generated Content Ownership</h3>
                            <p>
                                Subject to the terms and conditions herein, you shall own all right, title, and interest in and to any images, content, or output generated by the Service based on your User Content ("Generated Content"). You are granted a perpetual, irrevocable, worldwide, royalty-free, non-exclusive license to use, reproduce, distribute, display, perform, and create derivative works from the Generated Content for any lawful purpose, including commercial use.
                            </p>

                            <h3 className="text-xl font-semibold text-white/90">3.3 Commercial Use Rights</h3>
                            <p>
                                You may use the Generated Content for any commercial or non-commercial purpose without restriction, including but not limited to advertising, marketing, publication, sale, licensing, or any other commercial exploitation. No attribution to Beexel Graphics or Beexel Render Pro is required for such use.
                            </p>

                            <h3 className="text-xl font-semibold text-white/90">3.4 License Grant to Company</h3>
                            <p>
                                By uploading User Content to the Service, you grant us a limited, non-exclusive, royalty-free license to use, process, and store your User Content solely for the purpose of providing the Service to you. This license terminates when you delete your User Content or terminate your use of the Service.
                            </p>
                        </section>

                        <section className="space-y-4">
                            <h2 className="text-2xl font-bold text-white">4. Third-Party Technology and Service Providers</h2>
                            <h3 className="text-xl font-semibold text-white/90">4.1 Third-Party AI Services</h3>
                            <p>
                                Our Service incorporates third-party AI technologies and service providers, including but not limited to KIE AI, Stable Diffusion models, and other AI service providers. By using our Service, you acknowledge and agree that:
                            </p>
                            <ul className="list-disc pl-6 space-y-2">
                                <li>We are not responsible for the availability, performance, or reliability of third-party services</li>
                                <li>Third-party service failures, outages, or limitations may affect our Service</li>
                                <li>We are not liable for any issues, errors, or failures caused by third-party service providers</li>
                                <li>Third-party services may have their own terms of service and privacy policies</li>
                            </ul>

                            <h3 className="text-xl font-semibold text-white/90">4.2 Stable Diffusion License</h3>
                            <p>
                                Our Service incorporates Stable Diffusion technology, which is licensed under the CreativeML Open RAIL-M License ("RAIL License"). By using our Service, you acknowledge and agree to be bound by the terms and conditions of the RAIL License, which is incorporated herein by reference.
                            </p>

                            <h3 className="text-xl font-semibold text-white/90">4.3 Prohibited Uses and Content Restrictions</h3>
                            <p>You expressly agree not to use the Service to generate, create, or produce any content that:</p>
                            <ul className="list-disc pl-6 space-y-2">
                                <li>Is illegal, harmful, threatening, abusive, defamatory, or otherwise objectionable</li>
                                <li>Violates any applicable local, state, national, or international law or regulation</li>
                                <li>Infringes upon the rights of any third party, including intellectual property rights</li>
                                <li>Contains or promotes violence, self-harm, or dangerous activities</li>
                                <li>Discriminates against or harms individuals or groups based on race, gender, religion, nationality, disability, sexual orientation, or age</li>
                                <li>Violates human dignity or promotes hate speech</li>
                                <li>Contains sexually explicit, pornographic, or adult content</li>
                                <li>Is designed to deceive, mislead, or defraud</li>
                                <li>Contains malware, viruses, or other harmful code</li>
                            </ul>

                            <h3 className="text-xl font-semibold text-white/90">4.4 Compliance Monitoring</h3>
                            <p>
                                We reserve the right to monitor, review, and remove any content that violates these Terms or applicable laws. We may suspend or terminate your access to the Service immediately and without notice if you violate these restrictions.
                            </p>
                        </section>

                        <section className="space-y-4">
                            <h2 className="text-2xl font-bold text-white">5. Service Quality, Performance, and Limitations</h2>
                            <h3 className="text-xl font-semibold text-white/90">5.1 AI Technology Limitations</h3>
                            <p>
                                The Service utilizes artificial intelligence and machine learning technologies that are inherently probabilistic and may produce variable results. AI-generated content may not always meet your specific expectations, requirements, or quality standards. The output quality, accuracy, and suitability of generated content may vary significantly based on input parameters, content complexity, and other factors beyond our control.
                            </p>

                            <h3 className="text-xl font-semibold text-white/90">5.2 Third-Party Service Dependencies</h3>
                            <p>Our Service depends on third-party AI service providers and APIs. We are not responsible for:</p>
                            <ul className="list-disc pl-6 space-y-2">
                                <li>Third-party service outages, downtime, or technical failures</li>
                                <li>Changes in third-party service terms, pricing, or availability</li>
                                <li>Quality or accuracy of results from third-party AI services</li>
                                <li>Data processing delays or failures by third-party providers</li>
                                <li>Security breaches or data incidents at third-party services</li>
                            </ul>

                            <h3 className="text-xl font-semibold text-white/90">5.3 No Quality Guarantees</h3>
                            <p>
                                We make no representations, warranties, or guarantees regarding the quality, accuracy, completeness, or suitability of any Generated Content for your intended use. You acknowledge and agree that the Service is provided on an "as is" basis and that any reliance on the Service or Generated Content is at your own risk.
                            </p>

                            <h3 className="text-xl font-semibold text-white/90">5.4 Service Availability and Performance</h3>
                            <p>
                                We do not guarantee that the Service will be available at all times or that it will perform without interruption. The Service may be subject to scheduled maintenance, updates, technical difficulties, or third-party service issues that may temporarily affect availability or performance. We reserve the right to modify, suspend, or discontinue the Service at any time without notice.
                            </p>

                            <h3 className="text-xl font-semibold text-white/90">5.5 User Responsibility for Results</h3>
                            <p>
                                You acknowledge that the quality and suitability of Generated Content depends on various factors, including but not limited to the quality of input images, prompt specificity, and your specific requirements. You are solely responsible for evaluating and determining the suitability of any Generated Content for your intended use.
                            </p>
                        </section>

                        <section className="space-y-4">
                            <h2 className="text-2xl font-bold text-white">6. Payment Terms, Billing, and Refund Policy</h2>
                            <h3 className="text-xl font-semibold text-white/90">6.1 Payment Structure and Charges</h3>
                            <p>
                                Payment for the Service is based on computational resources consumed, including but not limited to server processing time, storage, bandwidth, and AI model inference costs. You are charged for the processing power and computational resources utilized to generate your content, not for the quality, accuracy, or suitability of the Generated Content.
                            </p>

                            <h3 className="text-xl font-semibold text-white/90">6.2 No Quality-Based Refunds</h3>
                            <p>
                                All payments are final and non-refundable. We do not provide refunds, tokens, or compensation based on the quality, attractiveness, accuracy, or suitability of Generated Content. Payment is for computational services rendered, and we do not guarantee specific outcomes or results from the AI processing.
                            </p>

                            <h3 className="text-xl font-semibold text-white/90">6.3 Payment Methods and Processing</h3>
                            <p>
                                We accept payments through various methods, including M-PESA and other approved payment processors. All payments must be made in advance before Service usage. You are responsible for all applicable taxes, fees, and charges associated with your use of the Service.
                            </p>

                            <h3 className="text-xl font-semibold text-white/90">6.4 Billing Disputes and Chargebacks</h3>
                            <p>
                                If you dispute any charges, you must contact us within thirty (30) days of the charge date. Unauthorized chargebacks or payment disputes may result in immediate suspension or termination of your account. We reserve the right to pursue collection of any outstanding amounts through appropriate legal means.
                            </p>
                        </section>

                        <section className="space-y-4">
                            <h2 className="text-2xl font-bold text-white">7. User Responsibilities and Obligations</h2>
                            <h3 className="text-xl font-semibold text-white/90">7.1 Content Rights and Permissions</h3>
                            <p>
                                You represent and warrant that you have all necessary rights, licenses, and permissions to upload, submit, and process any User Content through the Service. You are solely responsible for ensuring that your use of the Service and any Generated Content complies with all applicable laws and regulations.
                            </p>

                            <h3 className="text-xl font-semibold text-white/90">7.2 Prohibited Activities</h3>
                            <p>You agree not to engage in any of the following prohibited activities:</p>
                            <ul className="list-disc pl-6 space-y-2">
                                <li>Upload, submit, or process any content that infringes upon third-party intellectual property rights</li>
                                <li>Attempt to reverse engineer, decompile, or disassemble the Service or any underlying technology</li>
                                <li>Use automated systems, bots, or scripts to access or interact with the Service</li>
                                <li>Interfere with or disrupt the Service or servers connected to the Service</li>
                                <li>Violate any applicable local, state, national, or international law or regulation</li>
                                <li>Transmit any malicious code, viruses, or other harmful components</li>
                                <li>Impersonate any person or entity or misrepresent your affiliation with any person or entity</li>
                                <li>Collect or harvest any information from the Service without our express written consent</li>
                            </ul>

                            <h3 className="text-xl font-semibold text-white/90">7.3 Data Backup and Security</h3>
                            <p>
                                You are solely responsible for backing up and securing your User Content and Generated Content. We are not liable for any loss, corruption, or deletion of your content. You should maintain copies of all important content independently of the Service.
                            </p>

                            <h3 className="text-xl font-semibold text-white/90">7.4 Account Security</h3>
                            <p>
                                You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You must immediately notify us of any unauthorized use of your account or any other breach of security.
                            </p>
                        </section>

                        <section className="space-y-4">
                            <h2 className="text-2xl font-bold text-white">8. Limitation of Liability and Disclaimers</h2>
                            <div className="bg-white/5 p-6 rounded-lg border border-white/10 space-y-4">
                                <p>
                                    <strong>8.1 Limitation of Liability</strong><br />
                                    TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL BEEXEL GRAPHICS, ITS AFFILIATES, OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, OR LICENSORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO DAMAGES FOR LOSS OF PROFITS, DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES, ARISING OUT OF OR RELATING TO YOUR USE OF THE SERVICE, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
                                </p>
                                <p>
                                    <strong>8.2 Third-Party Service Liability</strong><br />
                                    WE ARE NOT LIABLE FOR ANY DAMAGES, LOSSES, OR ISSUES ARISING FROM THIRD-PARTY SERVICE PROVIDERS, INCLUDING BUT NOT LIMITED TO AI SERVICE PROVIDERS, PAYMENT PROCESSORS, OR OTHER THIRD-PARTY INTEGRATIONS. ANY ISSUES WITH THIRD-PARTY SERVICES ARE THE RESPONSIBILITY OF THE RESPECTIVE SERVICE PROVIDERS.
                                </p>
                                <p>
                                    <strong>8.3 Maximum Liability</strong><br />
                                    IN NO EVENT SHALL OUR TOTAL LIABILITY TO YOU FOR ALL DAMAGES, LOSSES, OR CAUSES OF ACTION EXCEED THE AMOUNT YOU HAVE PAID US IN THE TWELVE (12) MONTHS IMMEDIATELY PRECEDING THE EVENT GIVING RISE TO THE CLAIM, OR ONE HUNDRED DOLLARS ($100), WHICHEVER IS GREATER.
                                </p>
                                <p>
                                    <strong>8.4 Disclaimer of Warranties</strong><br />
                                    THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, OR COURSE OF PERFORMANCE. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, SECURE, OR ERROR-FREE.
                                </p>
                            </div>

                            <h3 className="text-xl font-semibold text-white/90">8.5 Force Majeure</h3>
                            <p>
                                We shall not be liable for any failure or delay in performance under these Terms due to circumstances beyond our reasonable control, including but not limited to acts of God, natural disasters, war, terrorism, labor disputes, government actions, technical failures, or third-party service provider issues.
                            </p>
                        </section>

                        <section className="space-y-4">
                            <h2 className="text-2xl font-bold text-white">9. Privacy, Data Protection, and Security</h2>
                            <h3 className="text-xl font-semibold text-white/90">9.1 Data Handling and Privacy</h3>
                            <p>
                                We respect your privacy and handle your data in accordance with our Privacy Policy, which is incorporated herein by reference. Your User Content is processed securely using industry-standard encryption and security measures. We do not permanently store your User Content unless required for Service operation or as otherwise specified in our Privacy Policy.
                            </p>

                            <h3 className="text-xl font-semibold text-white/90">9.2 Third-Party Data Processing</h3>
                            <p>
                                Your User Content may be processed by third-party AI service providers as part of the Service. We ensure that such processing is done in accordance with applicable privacy laws and our agreements with third-party providers. However, we are not responsible for the privacy practices or data handling of third-party service providers.
                            </p>

                            <h3 className="text-xl font-semibold text-white/90">9.3 Data Retention and Deletion</h3>
                            <p>
                                We retain your data only as long as necessary to provide the Service and comply with applicable laws. You may request deletion of your data at any time by contacting us. We will delete your data within thirty (30) days of receiving a valid deletion request, subject to legal and technical limitations.
                            </p>
                        </section>

                        <section className="space-y-4">
                            <h2 className="text-2xl font-bold text-white">10. Termination and Suspension</h2>
                            <h3 className="text-xl font-semibold text-white/90">10.1 Termination by User</h3>
                            <p>
                                You may terminate your use of the Service at any time by discontinuing use and contacting us to request account closure. Upon termination, your access to the Service will cease immediately.
                            </p>

                            <h3 className="text-xl font-semibold text-white/90">10.2 Termination by Company</h3>
                            <p>
                                We reserve the right to suspend or terminate your access to the Service immediately, without prior notice, if you violate these Terms, engage in prohibited activities, or for any other reason at our sole discretion. We may also suspend or terminate the Service itself at any time.
                            </p>

                            <h3 className="text-xl font-semibold text-white/90">10.3 Effect of Termination</h3>
                            <p>
                                Upon termination, your right to use the Service ceases immediately. We may delete your account and all associated data. Sections of these Terms that by their nature should survive termination shall remain in effect after termination.
                            </p>
                        </section>

                        <section className="space-y-4">
                            <h2 className="text-2xl font-bold text-white">11. Governing Law and Dispute Resolution</h2>
                            <h3 className="text-xl font-semibold text-white/90">11.1 Governing Law</h3>
                            <p>
                                These Terms shall be governed by and construed in accordance with the laws of Kenya, without regard to its conflict of law principles. Any legal action or proceeding arising under these Terms shall be brought exclusively in the courts of Kenya.
                            </p>

                            <h3 className="text-xl font-semibold text-white/90">11.2 Dispute Resolution</h3>
                            <p>
                                Before initiating any legal proceedings, you agree to first attempt to resolve any dispute through good faith negotiations. If such negotiations fail, disputes shall be resolved through binding arbitration in accordance with the rules of the Chartered Institute of Arbitrators (Kenya Branch).
                            </p>
                        </section>

                        <section className="space-y-4">
                            <h2 className="text-2xl font-bold text-white">12. Modifications to Terms</h2>
                            <h3 className="text-xl font-semibold text-white/90">12.1 Right to Modify</h3>
                            <p>
                                We reserve the right to modify, update, or change these Terms at any time in our sole discretion. We will notify users of material changes by posting the updated Terms on our website and updating the "Last updated" date. Your continued use of the Service after such modifications constitutes acceptance of the updated Terms.
                            </p>

                            <h3 className="text-xl font-semibold text-white/90">12.2 Severability</h3>
                            <p>
                                If any provision of these Terms is found to be unenforceable or invalid, such provision shall be limited or eliminated to the minimum extent necessary so that the remaining Terms shall remain in full force and effect and enforceable.
                            </p>
                        </section>

                        <section className="space-y-4">
                            <h2 className="text-2xl font-bold text-white">13. Miscellaneous Provisions</h2>
                            <h3 className="text-xl font-semibold text-white/90">13.1 Entire Agreement</h3>
                            <p>
                                These Terms, together with our Privacy Policy, constitute the entire agreement between you and Beexel Graphics regarding the use of the Service and supersede all prior and contemporaneous agreements, representations, and understandings.
                            </p>

                            <h3 className="text-xl font-semibold text-white/90">13.2 Assignment</h3>
                            <p>
                                You may not assign or transfer these Terms or your rights and obligations hereunder without our prior written consent. We may assign these Terms without restriction.
                            </p>

                            <h3 className="text-xl font-semibold text-white/90">13.3 Waiver</h3>
                            <p>
                                No waiver of any term or condition set forth in these Terms shall be deemed a further or continuing waiver of such term or condition or a waiver of any other term or condition.
                            </p>
                        </section>

                        <section className="space-y-4">
                            <h2 className="text-2xl font-bold text-white">14. Contact Information and Notices</h2>
                            <h3 className="text-xl font-semibold text-white/90">14.1 Contact Information</h3>
                            <p>
                                If you have any questions, concerns, or complaints about these Terms of Service, please contact us at:
                            </p>
                            <div className="bg-white/5 p-4 rounded-lg inline-block">
                                <p>Email: <a href="mailto:hello@beexelgraphics.com" className="text-cyan-400 hover:underline">hello@beexelgraphics.com</a></p>
                                <p>Company: Beexel Graphics</p>
                            </div>

                            <h3 className="text-xl font-semibold text-white/90">14.2 Notice Requirements</h3>
                            <p>
                                Any notices required under these Terms must be in writing and delivered to the contact information provided above. Notices shall be deemed received when delivered personally or by email.
                            </p>
                        </section>

                    </div>
                </div>
            </main>

            <Footer />
        </div>
    )
}
