import { NextRequest, NextResponse } from 'next/server'
import { requireAdmin } from '@/lib/modules/auth/session'
import { getAllCodes, createCode, createMultipleCodes, deleteCode, revokeCode, unrevokeCode } from '@/lib/modules/tokens/codes'
import { createErrorResponse } from '@/lib/utils/errors'

export const dynamic = 'force-dynamic'

export async function GET() {
  try {
    await requireAdmin()
    const codes = await getAllCodes()
    return NextResponse.json({
      success: true,
      codes,
    })
  } catch (error) {
    console.error('[API] Get codes error:', error)
    if (error instanceof Error && error.message === 'Unauthorized') {
      return NextResponse.json({
        success: false,
        msg: 'Unauthorized',
      }, { status: 401 })
    }
    return NextResponse.json(createErrorResponse(error), { status: 500 })
  }
}

export async function POST(request: NextRequest) {
  try {
    await requireAdmin()
    const body = await request.json()
    const { tokens, count, phoneNumber, amount, mpesaReceipt } = body

    if (!tokens || tokens <= 0) {
      return NextResponse.json({
        success: false,
        msg: 'Tokens must be a positive number',
      }, { status: 400 })
    }

    // Support bulk generation if count > 1
    const codeCount = count && count > 1 ? Math.min(count, 50) : 1 // Cap at 50

    if (codeCount > 1) {
      // Bulk generation
      const codes = await createMultipleCodes({
        tokens,
        count: codeCount,
        createdBy: 'admin',
      })

      return NextResponse.json({
        success: true,
        codes,
        count: codes.length,
      })
    } else {
      // Single code generation
      const code = await createCode({
        tokens,
        phoneNumber,
        amount,
        mpesaReceipt,
        createdBy: 'admin',
        autoGenerated: false,
      })

      return NextResponse.json({
        success: true,
        code: code.code,
        tokens: code.tokens,
      })
    }
  } catch (error) {
    console.error('[API] Generate code error:', error)
    if (error instanceof Error && error.message === 'Unauthorized') {
      return NextResponse.json({
        success: false,
        msg: 'Unauthorized',
      }, { status: 401 })
    }
    return NextResponse.json(createErrorResponse(error), { status: 500 })
  }
}

// PATCH for revoke/unrevoke
export async function PATCH(request: NextRequest) {
  try {
    await requireAdmin()
    const body = await request.json()
    const { code, action } = body

    if (!code) {
      return NextResponse.json({
        success: false,
        msg: 'Code is required',
      }, { status: 400 })
    }

    if (action === 'revoke') {
      const result = await revokeCode(code)
      return NextResponse.json(result)
    } else if (action === 'unrevoke') {
      const result = await unrevokeCode(code)
      return NextResponse.json(result)
    } else {
      return NextResponse.json({
        success: false,
        msg: 'Invalid action. Use "revoke" or "unrevoke"',
      }, { status: 400 })
    }
  } catch (error) {
    console.error('[API] Revoke code error:', error)
    if (error instanceof Error && error.message === 'Unauthorized') {
      return NextResponse.json({
        success: false,
        msg: 'Unauthorized',
      }, { status: 401 })
    }
    return NextResponse.json(createErrorResponse(error), { status: 500 })
  }
}

export async function DELETE(request: NextRequest) {
  try {
    await requireAdmin()
    const { searchParams } = request.nextUrl
    const code = searchParams.get('code')

    if (!code) {
      return NextResponse.json({
        success: false,
        msg: 'Code is required',
      }, { status: 400 })
    }

    await deleteCode(code)

    return NextResponse.json({
      success: true,
      msg: 'Code deleted',
    })
  } catch (error) {
    console.error('[API] Delete code error:', error)
    if (error instanceof Error && error.message === 'Unauthorized') {
      return NextResponse.json({
        success: false,
        msg: 'Unauthorized',
      }, { status: 401 })
    }
    return NextResponse.json(createErrorResponse(error), { status: 500 })
  }
}
